# Generated by Django 4.2.5 on 2023-09-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place_name',
            field=models.CharField(default='Default Place Name', max_length=100),
        ),
    ]
